# Generated by Django 5.2.7 on 2025-10-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_document_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
