# Generated by Django 5.2.7 on 2025-10-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_document_description'),
        ('myapp', '0005_document_pdf_file'),
    ]

    operations = [
    ]
