# Document processing rules
name: default
description: Default processing rules for AKN documents

safety:
  allow_text_changes: true  # Allow modifying document text
  allow_style_changes: true # Allow modifying styles and formatting

steps:
  - name: Remove Space After All List Numbers - 1
    select:
      document: true  # Apply to whole document
    actions:
      - word_recipe:
          name: no_space_after_number_all_lists_fix
          enabled: true
          description: Removes space after numbers in all list levels

  - name: Enforce List Level Indents (1-3) - 2
    select:
      document: true
    actions:
      - word_recipe:
          name: enforce_list_left_indents_level1to3
          enabled: true
          description: Sets consistent indents for list levels 1-3 (0.3, 0.6, 0.9 inches)

  - name: Remove All Tab Characters - 3
    select:
      document: true
    actions:
      - word_recipe:
          name: remove_all_tabs
          enabled: true
          description: Removes all tab characters to prevent formatting inconsistencies

  - name: Convert List Numbers to Em Dashes - 4
    select:
      document: true
    actions:
      - word_recipe:
          name: lists_dot_to_emdash
          enabled: true
          description: Converts list numbers followed by dots to em dashes (PAGES 1-4 ONLY, matching VBA)
          params:
            page_start: 1
            page_end: 4

  - name: Remove Spaces Around Em Dashes - 5
    select:
      document: true
    actions:
      - word_recipe:
          name: remove_spaces_around_em_dash
          enabled: true
          description: Cleans up formatting by removing unnecessary spaces around em dashes
          params:
            page_start: 1
            page_end: 999

  - name: Enforce Numeric List Alignment - 6
    select:
      document: true
    actions:
      - word_recipe:
          name: enforce_numeric_alignment_all_lists
          enabled: true
          description: Ensures consistent spacing and alignment of numbers in multilevel lists
          params:
            page_start: 1
            page_end: 999